version: "3"

services:
  
  anomaly_detection:

    image: anomaly_detection
    environment:
      - HOST=0.0.0.0
      - PORT=5001
    restart: 'always'
    ports:
      - "5001:5001"
    #volumes:
      # - ${PWD}/processed_data:/anomaly_detection/processed_data
      # - ${PWD}/anomaly_detection/config.yaml:/anomaly_detection/config.yaml