version: "3"

services:
  
  anomaly_detection:

    image: anomaly_detection
    restart: 'always'
    ports:
      - "5000:5000"
    #volumes:
      # - ${PWD}/processed_data:/anomaly_detection/processed_data
      # - ${PWD}/anomaly_detection/config.yaml:/anomaly_detection/config.yaml